import Head from 'next/head'
import Bot from "../assets/bot.png"
import Image from 'next/image'
import Link from 'next/link'

const fetcher = (url) => fetch(url).then((res) => res.json())

export default function Home() {

  return (
    <>
      <Head>
        <title>Alpha Chatbot: Ask me everything!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='w-full h-screen flex flex-col items-center justify-center text-center bg-gray-900'>
        <Image 
          src={Bot}
          height={150}
          width={150}
          alt='Bot'
          className='h-[150px] bg-gray-900'
        />
        <div className='lg:w-[400px] w-full mt-10 flex flex-col items-center'>
          <h1 className='text-3xl font-semibold p-4'>Hi, I'm Your intelligent conversational companion</h1>
          <p className='font-thin text-center'>This project is using OpenAI API</p>
        </div>
        <div className='mt-20'>
          <Link href={'/chatbot'}>
            <button
              type="button"
              className="border-2 border-blue-600 rounded-lg px-3 py-2 text-blue-400 cursor-pointer hover:bg-blue-600 hover:text-blue-200"
            >
              START CHAT
            </button>
          </Link>
        </div>
      </main>
    </>
  )
}