import Head from 'next/head'
import Navbar from '@/components/Navbar'

const fetcher = (url) => fetch(url).then((res) => res.json())

export default function Home() {

  return (
    <>
      <Head>
        <title>Alpha Chatbot: Ask me everything!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className='w-full h-screen flex flex-col items-center justify-center m-auto text-center'>
        <h1 className='uppercase text-2xl font-bold'>Chatbot and Image generator</h1>
        <p>This project is using OpenAI API</p>
        <Navbar />
      </body>
    </>
  )
}