import Head from 'next/head'
import Image from 'next/image'
import * as Icon from 'react-icons/io5'
import { useState } from 'react'
import Navbar from '@/components/Navbar'
import { BallTriangle } from 'react-loader-spinner'

const ImageGenerator = () => {
  const [question, setQuestion] = useState('');
  const [loading, setLoading] = useState(false);

  const [link, setLink] = useState('');

  function fetchResponse(e) {

    e.preventDefault();

    setLoading(true);

    const postData = async () => {
      const data = {
        question: question,
      };

      const fetchResponse = await fetch("/api/imagegen", {
        method: "POST",
        body: JSON.stringify(data),
      });
      return fetchResponse.json();
    };

    postData().then((res) => {

      const { data } = res;

      console.log(data.toString());

      setLink(`${data}`);

      setQuestion('')
      setLoading(false);
    });
  }


  return (
    <>
      <Head>
        <title>Alpha Chatbot: Tranfrom your imagination into image!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className='flex flex-col justify-between w-full'>

        <Navbar />

        {
          loading &&
          <div className='w-full flex flex-col items-center justify-center mt-5'>
            <BallTriangle
              height={100}
              width={100}
              radius={5}
              color="#4fa94d"
              ariaLabel="ball-triangle-loading"
              wrapperClass={{}}
              wrapperStyle=""
              visible={true}
            />
            <p className='text-3xl font-semibold animate-bounce mt-5'>Loading...</p>
          </div>
        }

        <div className='h-full pb-5'>
          {
            link && !loading &&
            <div className='w-full mt-2'>
              <Image
                src={link}
                height={500}
                width={500}
                alt='imagegenerated'
                className='m-auto'
              />
            </div>
          }
        </div>

        <form
          onSubmit={fetchResponse}
          className="bg-slate-900 p-2 border-t h-[100px] w-full lg:px-10 px-2 bottom-0 fixed"
        >
          <label for="search" className="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-white">Ask me everything</label>
          <div className="relative">
            <input
              type="text"
              id="text"
              className="block w-full p-4 lg:pl-10 pl-2 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
              placeholder="Type your imagination here..."
              required
              value={question}
              onChange={(e) => setQuestion(e.target.value)}
            />
            {
              question &&
              <button
                type="submit"
                className="text-white absolute right-5 bottom-2.5"
              >
                <Icon.IoSendOutline
                  size={32}
                  className="text-white hover:text-slate-500"
                />
              </button>
            }
          </div>
          <div className='text-center flex text-xs mt-2 gap-2'>
            <p className=''>Developer contact :</p>
            <a
              href="https://t.me/andrianarivoalpha"
              target='_blank'
              rel='noreferrer'
            >
              Telegram
            </a>
          </div>
        </form>
        <div className="p-2 h-[100px] w-full lg:px-10 px-2 bottom-0">
        </div>
      </body>
    </>
  )
}

export default ImageGenerator