import Head from 'next/head'
import Image from 'next/image'
import * as Icon from 'react-icons/io5'
import { useState } from 'react'
import { Comment } from 'react-loader-spinner'
import Logo from '../public/logo.png'
import { stringify } from 'postcss'

const fetcher = (url) => fetch(url).then((res) => res.json())

export default function Home() {

  const [question, setQuestion] = useState('');
  const [response, setResponse] = useState('');
  const [loading, setLoading] = useState(false);

  const [questionArray] = useState([]);
  const [responseArray] = useState([]);

  const datas = {
    question: questionArray,
    response: responseArray,
  }

  function fetchResponse(e) {

    e.preventDefault();
    setLoading(true);
    questionArray.push(question);

    const postData = async () => {
      const data = {
        question: question,
      };

      const response = await fetch("/api", {
        method: "POST",
        body: JSON.stringify(data),
      });
      setQuestion('')
      return response.json();
    };

    postData().then((response) => {
      const { data } = response;

      setResponse(data);
      responseArray.push(data);
      setLoading(false);
    });
  }

  return (
    <>
      <Head>
        <title>Alpha Chatbot: Ask me everything!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex flex-col w-full'>
        <form
          onSubmit={fetchResponse}
          className="w-full mb-6 lg:px-10 px-2 bottom-0 fixed"
        >
          <label for="search" className="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-white">Ask me everything</label>
          <div className="relative">
            <input
              type="text"
              id="text"
              className="block w-full p-4 lg:pl-10 pl-2 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
              placeholder="Type your question here..."
              required
              value={question}
              onChange={(e) => setQuestion(e.target.value)}
            />
            {
              question &&
              <button
                type="submit"
                className="text-white absolute right-5 bottom-2.5"
              >
                <Icon.IoSendOutline
                  size={32}
                  className="text-white hover:text-red-500"
                />
              </button>
            }
          </div>
          <div className='text-center flex text-xs mt-4 gap-2'>
            <p className=''>Developer contact :</p>
            <a
              href="https://t.me/andrianarivoalpha"
              target='_blank'
              rel='noreferrer'
            >
              Telegram
            </a>
          </div>
        </form>

        <div className='w-full flex flex-col'>
          <div className='w-full flex bg-slate-200 text-gray-800 py-5 lg:px-10 px-2 shadow-lg'>
            <Icon.IoPersonCircleSharp size={26} />
            <p>
              {
                question ? question
                  :
                  questionArray.length ? questionArray[questionArray.length - 1]
                    :
                    'Ask me something'
              }
            </p>
          </div>

          {
            !loading && response ?
              <div className='w-full flex gap-2 items-start lg:px-10 px-2 pt-5'>
                <Image
                  src={Logo}
                  height={60}
                  width={60}
                  alt='openai-logo'
                  className='bg-white h-10 w-10 object-cover rounded-full'
                />
                <p className='p-5 bg-slate-500 rounded-2xl'>
                  {response && response}
                </p>
              </div>
              :
              <div className='w-full flex gap-2 items-start lg:px-10 px-2 pt-5'>
                <Image
                  src={Logo}
                  height={60}
                  width={60}
                  alt='openai-logo'
                  className='bg-white h-10 w-10 object-cover rounded-full'
                />
                <Comment
                  visible={true}
                  height="80"
                  width="80"
                  ariaLabel="comment-loading"
                  wrapperStyle={{}}
                  wrapperClass="comment-wrapper"
                  color="#fff"
                  backgroundColor="#F4442E"
                />
              </div>
          }

          {/* {
            questionArray &&
            Object.keys(datas)
              .map((key, index) => {
                return (
                  <div key={key}>
                    <p></p>
                  </div>
                )
              })
          } */}
          <div>

          </div>
        </div>
      </main>
    </>
  )
}