import Head from 'next/head'
import Image from 'next/image'
import * as Icon from 'react-icons/io5'
import { useState } from 'react'
import { Comment } from 'react-loader-spinner'
import Logo from '../public/logo.png'
import User from '../public/user.png'

const fetcher = (url) => fetch(url).then((res) => res.json())

export default function Home() {

  const [question, setQuestion] = useState('');
  const [loading, setLoading] = useState(false);

  const [datas, setData] = useState([]);

  function fetchResponse(e) {

    e.preventDefault();

    setLoading(true);

    const postData = async () => {
      const data = {
        question: question,
      };

      const fetchResponse = await fetch("/api", {
        method: "POST",
        body: JSON.stringify(data),
      });
      return fetchResponse.json();
    };

    postData().then((res) => {
      const { data } = res;

      const obj = { question: question, response: data }
      console.log(obj);

      datas.push(obj);

      console.log(datas);

      setQuestion('')
      setLoading(false);
    });
  }


  return (
    <>
      <Head>
        <title>Alpha Chatbot: Ask me everything!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className='flex flex-col justify-between w-full'>
        
        {/* profile */}
        <div className='fixed h-[80px] w-full flex bg-slate-900 text-gray-50 py-5 lg:px-10 px-2 shadow-lg border-b'>
          <Image
            src={Logo}
            height={60}
            width={60}
            alt='openai-logo'
            className='bg-white h-10 w-10 object-cover rounded-full'
          />
          <p className='py-2 px-5'>@Allpha_ChatBot</p>
        </div>

        <div className='h-[80px] w-full flex bg-slate-900 text-gray-50 py-5 lg:px-10 px-2 shadow-lg border-b'>
        </div>

        {/* Conversation */}
        <div className='h-full pb-5'>
          {
            datas &&
            Object.keys(datas)
              .map((key, index) => {
                console.log(key)
                return (
                  <div
                    key={key}
                    className='w-full flex flex-col gap-2 items-start lg:px-10 px-2 pt-5'
                  >
                    <div className='w-full flex items-start justify-end gap-2'>
                      <p className='py-2 px-5 bg-blue-500 rounded-l-xl rounded-b-xl'>{datas[key].question}</p>
                      <Image
                        src={User}
                        height={60}
                        width={60}
                        alt='openai-logo'
                        className='bg-white h-10 w-10 object-cover rounded-full'
                      />
                    </div>
                    <div className='w-full flex items-start justify-start gap-2'>
                      <Image
                        src={Logo}
                        height={60}
                        width={60}
                        alt='openai-logo'
                        className='bg-white h-10 w-10 object-cover rounded-full'
                      />
                      <p className='py-2 px-5 bg-slate-500 rounded-r-xl rounded-b-xl'>{datas[key].response}</p>
                    </div>
                  </div>
                )
              })
          }
        </div>

        <form
          onSubmit={fetchResponse}
          className="bg-slate-900 p-2 border-t h-[100px] w-full lg:px-10 px-2 bottom-0 fixed"
        >
          <label for="search" className="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-white">Ask me everything</label>
          <div className="relative">
            <input
              type="text"
              id="text"
              className="block w-full p-4 lg:pl-10 pl-2 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
              placeholder="Type your question here..."
              required
              value={question}
              onChange={(e) => setQuestion(e.target.value)}
            />
            {
              question &&
              <button
                type="submit"
                className="text-white absolute right-5 bottom-2.5"
              >
                <Icon.IoSendOutline
                  size={32}
                  className="text-white hover:text-slate-500"
                />
              </button>
            }
          </div>
          <div className='text-center flex text-xs mt-2 gap-2'>
            <p className=''>Developer contact :</p>
            <a
              href="https://t.me/andrianarivoalpha"
              target='_blank'
              rel='noreferrer'
            >
              Telegram
            </a>
          </div>
        </form>
        <div className="p-2 h-[100px] w-full lg:px-10 px-2 bottom-0">
        </div>
      </body>
    </>
  )
}